# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 진영인
title: 백엔드 개발자
email: zero0515@gmail.com
phone: 010-9194-0785
# website: https://velog.io/@zero013/posts

# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username: sabsiru
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: j__y__i
linkedin_username: 영인-진-68212a362
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links: # Optional, remove if not needed
  - title: velog
    icon: fas fa-blog
    url: https://velog.io/@zero013/posts
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)
# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
about_profile_image: images/5.JPG
about_content: | # this will include new lines to allow paragraphs
  - Java와 Spring 기반으로 안정적이고 유지보수 가능한 백엔드 시스템을 구축해온 개발자입니다. 실무에서는 운영 환경 간 차이로 
  인해 발생한 실서비스 장애를 Flashback Query를 통해 빠르게 복구하고, 통계 집계 누락 문제를 SQL 분석과 로그 검증을 통해 
  정합성 있게 보정하는 등 장애 대응과 데이터 신뢰성 확보에 주력해 왔습니다. 기능 안정성과 코드 신뢰성을 확보하기 위해 테스트 
  코드 기반 개발을 지향하고 있습니다.
  - 현업에서 마주치는 다양한 기술적 요구사항에 대응하기 위해 QueryDSL, JPA, Redis, Docker, Git/GitHub 등을 중심으로 사이드 
  프로젝트와 부트캠프 과정을 통해 학습과 실습을 병행해왔습니다. DDD와 Facade 패턴 등 구조적 설계를 적용한 커뮤니티 프로젝트를 
  통해 도메인 기반 설계와 테스트 주도 개발을 경험했고, 부하 테스트(k6), 캐싱 전략, 분산락 등 대용량 처리와 확장성 확보를 위한 
  기술에 실전 감각을 길러왔습니다.

content:
  #  - title: Projects # Title for the section
  #    layout: list # Type of content section (list/text)
  #    content:
  #      - layout: top-middle
  #        title: Super awesome project
  #        link: github.com/sproogen
  #        # link_text: Project Website
  #        additional_links:
  #          - title:  sproogen/modern-resume-theme
  #            icon: fab fa-github
  #            url: github.com/sproogen/modern-resume-theme
  #          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #          #   icon: fab fa-github
  #          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #        quote: >
  #          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #        description: | # this will include new lines to allow paragraphs
  #          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Skill
    layout: list
    content:
      - layout: top-middle
        quote: >
          업무에 사용 했던 기술들과 개인적으로 공부하고 있는 기술들입니다.

      - layout: left
        title: Backend
        description: | # this will include new lines to allow paragraphs
          - Java
          - Spring MVC, Spring Boot
          - JPA, MyBatis
          - Junit5, Mockito
          - IntelliJ, DataGrip, Git

      - layout: left
        title: Devops
        description: | # this will include new lines to allow paragraphs
          - MySQL, Oracle
          - Redis, Docker

      - layout: left
        title: Frontend
        description: | # this will include new lines to allow paragraphs
          - JavaScript
          - HTML, CSS

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 루트시스템즈
        sub_title: 웹 개발자 | 경찰청 사회적약자 시스템 유지보수팀 파견
        caption: 2023.05 ~ 2024.12
        quote: >
          전자정부프레임워크1, Java 1.7, JSP, Oracle, iBatis, JavaScript, jQuery, Ajax, HTML, CSS
        description: |
          - 반복적으로 발생하던 사전등록 아동 보호자 조회 오류를 분석해, 특정 조건에서만 발생하는 로직 문제를 확인하고 원인 코드를 추적함. 해당 문제는 웹에서는 검증이 존재하지만 모바일에서는 검증이 누락되어 발생한 것으로, 외부 인력이 담당하는 모바일 개발팀에 이슈를 인계하여 수정 가능하도록 조치함.
          - 실종자 상세보기에서 다수의 조회 오류가 발생하여, 생년월일과 주민등록번호 입력값 중 ‘13월’, ‘32일’ 등 비정상 데이터가 존재함을 확인함. 정규 표현식 기반 쿼리로 비정상 데이터를 식별하고, 기준이 명확한 항목에 대해 일괄 정정 처리함. 해당 문제 역시 모바일 입력 검증 누락으로 인해 발생한 것임.
          - 게시판 항목 및 순서 수정 작업 중 운영 DB와 개발 DB 간 코드 미동기화로 인해 유니크 제약 위반 발생. Flashback Query로 1시간 전 상태를 복원하고 데이터 정합성을 맞춰 메인 페이지 정상화 조치함.
          - 내부 담당자의 요청으로 월간 통계 수치에서 약 9.7% 누락 현상을 확인. 외부 사용자의 입력 데이터는 존재했으나, 집계 로직의 조건과 맞지 않아 통계에서 제외된 것으로 분석됨. 폐쇄망(경찰청 내부망) 환경에서 직접적인 재현은 어려웠지만, 로그와 데이터 이력을 분석해 누락 항목을 보정하여 통계 정확도를 100%로 복구.
          - 경찰청 내부 요청으로 100만 건 이상 규모의 테이블에서 다수 테이블 조인, 복잡한 조건 분기, 공통 코드 매핑 등을 포함한 SQL 쿼리를 구성하여 통계 데이터를 정기적으로 추출 및 전달함.
          - 매년 수동으로 수정하던 외부 인력용 ID 생성 로직을 LocalDate 기반 자동화로 개선함.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 항해+ 백엔드 코스 8기
        caption: 2025.03 ~ 2025.06
        link: https://github.com/sabsiru/eCommerce-service
        # sub_title: BSc Computer Science
        quote: >
          Java 17, Spring Boot 3, JPA, MySQL, Redis, Docker, k6, Grafana
        description: | # this will include new lines to allow paragraphs
          - 테스트 주도 개발(TDD)을 기반으로 작은 단위 서비스 구현 경험을 통해 테스트 코드 작성 및 리팩토링 흐름 이해
          - ERD, 시퀀스/클래스 다이어그램 등을 작성하며 설계 중심 개발 경험 축적
          - 주문, 결제, 쿠폰 발급, 포인트 충전/사용 기능을 포함한 E-Commerce 서비스 개발
          - Clean Architecture, DDD, Facade 패턴 등을 적용하여 계층 간 책임을 분리한 구조 설계
          - 조회 성능 병목 구간을 찾아 k6 기반 부하 테스트를 수행하고, Redis Cache 및 Sorted Set으로 성능 개선
          - 포인트/재고/쿠폰 등 주요 리소스에 대해 비관적 락/낙관적 락/Redis 기반 분산락을 적용하고, 동시성 테스트(Red-Green) 후 보고서 작성
          - Redis를 활용한 선착순 쿠폰 발급 시스템 및 인기상품 캐싱 기능 구현
          - 외부 주문 연동을 위한 이벤트 기반 아키텍처 구현 경험 (Spring 이벤트 사용)
      - layout: left
        title: 미래IT캠퍼스 융합소프트웨어 개발자 양성 과정
        caption: 2022.11 ~ 2023.04
        link: https://github.com/sabsiru/virtualland-indv
        # sub_title: BSc Computer Science
        quote: >
          Java 1.8, Spring MVC, JavaScript, Oracle, MyBatis, jQuery, Ajax, HTML, CSS
        description: | # this will include new lines to allow paragraphs
          - Java 기초 문법 학습 후, HTML, CSS, JavaScript로 웹 페이지의 구조와 동작 원리 학습
          - Spring 레거시 구조(Servlet 기반)를 활용해 JSP로 게시판 기능을 직접 구현
          - 이후 jQuery, Ajax를 학습하며 웹의 동적인 요소와 비동기 통신 방식에 대한 이해를 확장
          - 학습한 내용을 바탕으로 Oracle과 MyBatis를 활용한 팀 프로젝트를 통해 CRUD 기반 웹 애플리케이션을 구현
          - Windows 환경 기준의 실습과 달리 macOS에서 Docker로 Oracle을 구성하며 Apple Silicon 이슈를 겪었고, 관련 문제를 스스로 해결하며 학습을 지속함
          - 전체적으로 레거시 웹 개발의 흐름을 따라가며 프론트부터 백엔드, DB 연동까지의 기초를 실습함

  - title: Side Project
    layout: list
    content:
      - layout: left
        title: 콘소메 커뮤니티 프로젝트 (가칭) | 커뮤니티 서비스 구현 중 (진행 중)
        caption: 2025.6 ~ 현재
        link: GitHubGitHub - sabsiru/consome-back/posts
        quote: >
          Java 17, Spring Boot 3, JPA, MySQL, Docker, k6, Grafana, (Redis)
        description: |
          - 클린 아키텍처 + 레이어드 아키텍처 기반으로 커뮤니티 웹 서비스 구조 설계
          - 사용자, 게시판, 댓글, 좋아요, 포인트 도메인을 도출하고 DDD 패턴에 따라 구현
          - 포인트 히스토리를 통한 행위 기반 포인트 적립 구조 설계 및 개발
          - 대댓글, 논리 삭제(Y/N 플래그), 자기 참조 댓글 구조 등 계층형 데이터 처리 구조 설계
          - 테스트 주도 개발(TDD)을 통해 핵심 도메인에 대한 단위 테스트 작성 및 안정성 확보
          - 각 도메인에 대해 독립적으로 개발하고 Facade 패턴 적용

  - title: Others
    layout: list
    content:
      - layout: left
        title: 개인사업(의류 및 액세서리 판매)
        caption: 2020.03 ~ 2022.10
        quote: >
          네이버 스마트스토어 운영
        description: |
          - 동대문시장에서 직접 상품을 떼다 촬영하고 편집 후 업로드

      - layout: left
        title: 제이에이치스타일
        caption: 2018.12 ~ 2020.01
        quote: >
          남성 의류 쇼핑몰 촬영 업무
        description: |
          - 상품위주의 촬영과 주1회 모델 촬영 및 상품 포장

     # - layout: left
      #  title: 비전사진학원
       # caption: 2018.03 ~ 2018.12
        #quote: >
         # 사진학원 조교
       # description: |
       #   - 데스크 업무와 수업에 조교로 참여

#      - layout: left
#        title: 병역
#        caption: 2014.10 ~ 2016.07
#        quote: >
#          9사단 헌병 운전병 병장 만기전역
#        description: |
#          - 호송, 감호, 경호 등 운전업무 수행

#      - layout: left
#        title: 태흥시네마
#        caption: 2013.03 ~ 2014.03
#        quote: >
#          의정부 개인 영화상영관
#        description: |
#          - 매점, 매표, 영화관 정리 및 업무 스케쥴 관리

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      개발 외 흥미를 느끼는 것들:
      - 루빅스 큐브

      ![3](/images/3.jpg "Trees")


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
