# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 진영인
title: 백엔드 개발자
email: zero0515@gmail.com
phone: 010-9194-0785
# website: https://github.com/sabsiru

# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username: sabsiru
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: j__y__i
linkedin_username: 영인-진-68212a362
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
about_profile_image: images/me.JPG
about_content: | # this will include new lines to allow paragraphs
  - 안녕하세요. 1년 6개월차 백엔드 개발자 진영인입니다.  
  - <mark>대화</mark>를 즐기고, 상대방의 이야기에 <mark>경청</mark>하려고 노력합니다.
  - 무언가를 만들어낸다는 점에 매력을 느껴 개발을 시작했습니다.
  - <mark>읽기 쉬운 코드</mark>가 좋은 코드라 생각하며, <mark>테스트 코드</mark>의 중요성도 잘 알고 있습니다.
  - 기술에 <mark>매몰</mark>되지 않고 문제의 <mark>본질</mark>을 파악하는 것이 결국 내 것이 되는 길이라고 생각합니다.

content:
  #  - title: Projects # Title for the section
  #    layout: list # Type of content section (list/text)
  #    content:
  #      - layout: top-middle
  #        title: Super awesome project
  #        link: github.com/sproogen
  #        # link_text: Project Website
  #        additional_links:
  #          - title:  sproogen/modern-resume-theme
  #            icon: fab fa-github
  #            url: github.com/sproogen/modern-resume-theme
  #          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #          #   icon: fab fa-github
  #          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #        quote: >
  #          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #        description: | # this will include new lines to allow paragraphs
  #          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Skill
    layout: list
    content:
      - layout: top-middle
        quote: >
          업무에 사용 했던 기술들과 개인적으로 공부하고 있는 기술들입니다.

      - layout: left
        title: Backend
        description: | # this will include new lines to allow paragraphs
          - Java
          - Spring MVC, Spring Boot
          - JPA
          - Junit5, Mockito
          - IntelliJ, DataGrip
          - Git

      - layout: left
        title: Devops
        description: | # this will include new lines to allow paragraphs
          - MySQL, Oracle
          - Redis

      - layout: left
        title: Frontend
        description: | # this will include new lines to allow paragraphs
          - JavaScript
          - jQuery, Ajax

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 루트시스템즈
        sub_title: 웹 개발자
        caption: 2023.05 ~ 2024.12
        quote: >
          SI 회사
        description: |
          - 전자정부 프레임워크 기반의 레거시 시스템 유지보수 및 기능 개선 업무 수행
          - 외부인력용 ID 생성 시 매년 하드코딩으로 변경하던 연도 접두어(sYY)를 서버 시간 기반으로 자동 반영되도록 개선
          - 사용자의 예상 대비 약 10% 누락된 통계 수치를 확인하고, 로그와 입력 흐름을 검토해 원인을 파악한 뒤 필요한 데이터를 보정하여 100% 일치하도록 수정

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 항해+ 백엔드 코스 8기
        caption: 2025.03 ~ 2025.06
        link: https://github.com/sabsiru/eCommerce-service
        # sub_title: BSc Computer Science
        quote: >
          대용량 트래픽 경험이 필요한 주니어 백엔드 개발자를 위한 과정
        description: | # this will include new lines to allow paragraphs
          - 단위 테스트와 통합 테스트를 통해 테스트 주도 개발(TDD) 방식의 개발 흐름을 익힘
          - ERD, 시퀀스 다이어그램, 클래스 다이어그램 등 다양한 설계 문서를 작성하고 이를 기반으로 실제 프로젝트 구현
          - 기능 개발과 함께 단위 테스트, 통합 테스트, E2E 테스트를 작성하며 전체 시스템 흐름을 검증
          - 동시성 이슈를 재현하고, 비관적 락과 낙관적 락을 적용해 안정적으로 문제를 해결
          - 이후 Redis 기반의 Redisson 분산 락으로 구조를 리팩토링하여 분산 환경에서도 동시성 이슈를 방어
          - 복잡한 조회 로직으로 인해 부하가 발생하기 쉬운 API에 Redis 캐시를 적용하여 응답 속도 개선 및 부하 분산
          - 트래픽이 집중되는 기능에도 Redis를 적용해 구조를 개선하고 안정성을 확보
          - 트랜잭션 일관성이 중요한 핵심 서비스 흐름을 이벤트 기반 구조로 리팩토링하여 처리 순서와 응답 분리를 구현

      - layout: left
        title: 미래IT캠퍼스 융합소프트웨어 개발자 양성
        caption: 2022.11 ~ 2023.04
        link: https://github.com/sabsiru/virtualland-indv
        # sub_title: BSc Computer Science
        quote: >
          기본적인 CRUD 위주의 레거시 프로젝트
        description: | # this will include new lines to allow paragraphs
          - Java 기초 문법 학습 후, HTML, CSS, JavaScript로 웹 페이지의 구조와 동작 원리 학습
          - Spring 레거시 구조(Servlet 기반)를 활용해 JSP로 게시판 기능을 직접 구현
          - 이후 jQuery, Ajax를 학습하며 웹의 동적인 요소와 비동기 통신 방식에 대한 이해를 확장
          - 학습한 내용을 바탕으로 Oracle과 MyBatis를 활용한 팀 프로젝트를 통해 CRUD 기반 웹 애플리케이션을 구현
          - Windows 환경 기준의 실습과 달리 macOS에서 Docker로 Oracle을 구성하며 Apple Silicon 이슈를 겪었고, 관련 문제를 스스로 해결하며 학습을 지속함
          - 전체적으로 레거시 웹 개발의 흐름을 따라가며 프론트부터 백엔드, DB 연동까지의 기초를 실습함

  - title: Others
    layout: list
    content:
      - layout: left
        title: 개인사업(의류 및 액세서리 판매)
        caption: 2020.03 ~ 2022.10
        quote: >
          네이버 스마트스토어 운영
        description: |
          - 동대문시장에서 직접 상품을 떼다 촬영하고 편집 후 업로드

      - layout: left
        title: 제이에이치스타일
        caption: 2018.12 ~ 2020.01
        quote: >
          남성 의류 쇼핑몰 촬영 업무
        description: |
          - 상품위주의 촬영과 주1회 모델 촬영 및 상품 포장

      - layout: left
        title: 비전사진학원
        caption: 2018.03 ~ 2018.12
        quote: >
          사진학원 조교
        description: |
          - 데스크 업무와 수업에 조교로 참여

      - layout: left
        title: 병역
        caption: 2014.10 ~ 2016.07
        quote: >
          9사단 헌병 운전병 병장 만기전역
        description: |
          - 호송, 감호, 경호 등 운전업무 수행

      - layout: left
        title: 태흥시네마
        caption: 2013.03 ~ 2014.03
        quote: >
          의정부 개인 영화상영관
        description: |
          - 매점, 매표, 영화관 정리 및 업무 스케쥴 관리

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      개발 외 흥미를 느끼는 것들:
      - 루빅스 큐브
      - 노래
      - 생산성, 편의성 프로그램 찾기
      - 축구, 야구 보기
      - 사진 찍기

      ![3](/images/3.jpg "Trees")


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
